// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Requests/RequestType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOLib.Pokemon.Proto.Requests {

  /// <summary>Holder for reflection information generated from Requests/RequestType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class RequestTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Requests/RequestType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpSZXF1ZXN0cy9SZXF1ZXN0VHlwZS5wcm90bxIeUE9HT0xpYi5Qb2tlbW9u",
            "LlByb3RvLlJlcXVlc3RzKsEMCgtSZXF1ZXN0VHlwZRIQCgxNRVRIT0RfVU5T",
            "RVQQABIRCg1QTEFZRVJfVVBEQVRFEAESDgoKR0VUX1BMQVlFUhACEhEKDUdF",
            "VF9JTlZFTlRPUlkQBBIVChFET1dOTE9BRF9TRVRUSU5HUxAFEhsKF0RPV05M",
            "T0FEX0lURU1fVEVNUExBVEVTEAYSIgoeRE9XTkxPQURfUkVNT1RFX0NPTkZJ",
            "R19WRVJTSU9OEAcSDwoLRk9SVF9TRUFSQ0gQZRINCglFTkNPVU5URVIQZhIR",
            "Cg1DQVRDSF9QT0tFTU9OEGcSEAoMRk9SVF9ERVRBSUxTEGgSDAoISVRFTV9V",
            "U0UQaRITCg9HRVRfTUFQX09CSkVDVFMQahIXChNGT1JUX0RFUExPWV9QT0tF",
            "TU9OEG4SFwoTRk9SVF9SRUNBTExfUE9LRU1PThBvEhMKD1JFTEVBU0VfUE9L",
            "RU1PThBwEhMKD1VTRV9JVEVNX1BPVElPThBxEhQKEFVTRV9JVEVNX0NBUFRV",
            "UkUQchIRCg1VU0VfSVRFTV9GTEVFEHMSEwoPVVNFX0lURU1fUkVWSVZFEHQS",
            "EAoMVFJBREVfU0VBUkNIEHUSDwoLVFJBREVfT0ZGRVIQdhISCg5UUkFERV9S",
            "RVNQT05TRRB3EhAKDFRSQURFX1JFU1VMVBB4EhYKEkdFVF9QTEFZRVJfUFJP",
            "RklMRRB5EhEKDUdFVF9JVEVNX1BBQ0sQehIRCg1CVVlfSVRFTV9QQUNLEHsS",
            "EAoMQlVZX0dFTV9QQUNLEHwSEgoORVZPTFZFX1BPS0VNT04QfRIUChBHRVRf",
            "SEFUQ0hFRF9FR0dTEH4SHwobRU5DT1VOVEVSX1RVVE9SSUFMX0NPTVBMRVRF",
            "EH8SFQoQTEVWRUxfVVBfUkVXQVJEUxCAARIZChRDSEVDS19BV0FSREVEX0JB",
            "REdFUxCBARIRCgxVU0VfSVRFTV9HWU0QhQESFAoPR0VUX0dZTV9ERVRBSUxT",
            "EIYBEhUKEFNUQVJUX0dZTV9CQVRUTEUQhwESDwoKQVRUQUNLX0dZTRCIARIb",
            "ChZSRUNZQ0xFX0lOVkVOVE9SWV9JVEVNEIkBEhgKE0NPTExFQ1RfREFJTFlf",
            "Qk9OVVMQigESFgoRVVNFX0lURU1fWFBfQk9PU1QQiwESGwoWVVNFX0lURU1f",
            "RUdHX0lOQ1VCQVRPUhCMARIQCgtVU0VfSU5DRU5TRRCNARIYChNHRVRfSU5D",
            "RU5TRV9QT0tFTU9OEI4BEhYKEUlOQ0VOU0VfRU5DT1VOVEVSEI8BEhYKEUFE",
            "RF9GT1JUX01PRElGSUVSEJABEhMKDkRJU0tfRU5DT1VOVEVSEJEBEiEKHENP",
            "TExFQ1RfREFJTFlfREVGRU5ERVJfQk9OVVMQkgESFAoPVVBHUkFERV9QT0tF",
            "TU9OEJMBEhkKFFNFVF9GQVZPUklURV9QT0tFTU9OEJQBEhUKEE5JQ0tOQU1F",
            "X1BPS0VNT04QlQESEAoLRVFVSVBfQkFER0UQlgESGQoUU0VUX0NPTlRBQ1Rf",
            "U0VUVElOR1MQlwESFQoQR0VUX0FTU0VUX0RJR0VTVBCsAhIWChFHRVRfRE9X",
            "TkxPQURfVVJMUxCtAhIcChdHRVRfU1VHR0VTVEVEX0NPREVOQU1FUxCRAxId",
            "ChhDSEVDS19DT0RFTkFNRV9BVkFJTEFCTEUQkgMSEwoOQ0xBSU1fQ09ERU5B",
            "TUUQkwMSDwoKU0VUX0FWQVRBUhCUAxIUCg9TRVRfUExBWUVSX1RFQU0QlQMS",
            "GwoWTUFSS19UVVRPUklBTF9DT01QTEVURRCWAxIWChFMT0FEX1NQQVdOX1BP",
            "SU5UUxD0AxIJCgRFQ0hPEJoFEhsKFkRFQlVHX1VQREFURV9JTlZFTlRPUlkQ",
            "vAUSGAoTREVCVUdfREVMRVRFX1BMQVlFUhC9BRIXChJTRklEQV9SRUdJU1RS",
            "QVRJT04QoAYSFQoQU0ZJREFfQUNUSU9OX0xPRxChBhIYChNTRklEQV9DRVJU",
            "SUZJQ0FUSU9OEKIGEhEKDFNGSURBX1VQREFURRCjBhIRCgxTRklEQV9BQ1RJ",
            "T04QpAYSEQoMU0ZJREFfRE9XU0VSEKUGEhIKDVNGSURBX0NBUFRVUkUQpgZi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOLib.Pokemon.Proto.Requests.RequestType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum RequestType {
    [pbr::OriginalName("METHOD_UNSET")] MethodUnset = 0,
    [pbr::OriginalName("PLAYER_UPDATE")] PlayerUpdate = 1,
    [pbr::OriginalName("GET_PLAYER")] GetPlayer = 2,
    [pbr::OriginalName("GET_INVENTORY")] GetInventory = 4,
    [pbr::OriginalName("DOWNLOAD_SETTINGS")] DownloadSettings = 5,
    [pbr::OriginalName("DOWNLOAD_ITEM_TEMPLATES")] DownloadItemTemplates = 6,
    [pbr::OriginalName("DOWNLOAD_REMOTE_CONFIG_VERSION")] DownloadRemoteConfigVersion = 7,
    [pbr::OriginalName("FORT_SEARCH")] FortSearch = 101,
    [pbr::OriginalName("ENCOUNTER")] Encounter = 102,
    [pbr::OriginalName("CATCH_POKEMON")] CatchPokemon = 103,
    [pbr::OriginalName("FORT_DETAILS")] FortDetails = 104,
    [pbr::OriginalName("ITEM_USE")] ItemUse = 105,
    [pbr::OriginalName("GET_MAP_OBJECTS")] GetMapObjects = 106,
    [pbr::OriginalName("FORT_DEPLOY_POKEMON")] FortDeployPokemon = 110,
    [pbr::OriginalName("FORT_RECALL_POKEMON")] FortRecallPokemon = 111,
    [pbr::OriginalName("RELEASE_POKEMON")] ReleasePokemon = 112,
    [pbr::OriginalName("USE_ITEM_POTION")] UseItemPotion = 113,
    [pbr::OriginalName("USE_ITEM_CAPTURE")] UseItemCapture = 114,
    [pbr::OriginalName("USE_ITEM_FLEE")] UseItemFlee = 115,
    [pbr::OriginalName("USE_ITEM_REVIVE")] UseItemRevive = 116,
    [pbr::OriginalName("TRADE_SEARCH")] TradeSearch = 117,
    [pbr::OriginalName("TRADE_OFFER")] TradeOffer = 118,
    [pbr::OriginalName("TRADE_RESPONSE")] TradeResponse = 119,
    [pbr::OriginalName("TRADE_RESULT")] TradeResult = 120,
    [pbr::OriginalName("GET_PLAYER_PROFILE")] GetPlayerProfile = 121,
    [pbr::OriginalName("GET_ITEM_PACK")] GetItemPack = 122,
    [pbr::OriginalName("BUY_ITEM_PACK")] BuyItemPack = 123,
    [pbr::OriginalName("BUY_GEM_PACK")] BuyGemPack = 124,
    [pbr::OriginalName("EVOLVE_POKEMON")] EvolvePokemon = 125,
    [pbr::OriginalName("GET_HATCHED_EGGS")] GetHatchedEggs = 126,
    [pbr::OriginalName("ENCOUNTER_TUTORIAL_COMPLETE")] EncounterTutorialComplete = 127,
    [pbr::OriginalName("LEVEL_UP_REWARDS")] LevelUpRewards = 128,
    [pbr::OriginalName("CHECK_AWARDED_BADGES")] CheckAwardedBadges = 129,
    [pbr::OriginalName("USE_ITEM_GYM")] UseItemGym = 133,
    [pbr::OriginalName("GET_GYM_DETAILS")] GetGymDetails = 134,
    [pbr::OriginalName("START_GYM_BATTLE")] StartGymBattle = 135,
    [pbr::OriginalName("ATTACK_GYM")] AttackGym = 136,
    [pbr::OriginalName("RECYCLE_INVENTORY_ITEM")] RecycleInventoryItem = 137,
    [pbr::OriginalName("COLLECT_DAILY_BONUS")] CollectDailyBonus = 138,
    [pbr::OriginalName("USE_ITEM_XP_BOOST")] UseItemXpBoost = 139,
    [pbr::OriginalName("USE_ITEM_EGG_INCUBATOR")] UseItemEggIncubator = 140,
    [pbr::OriginalName("USE_INCENSE")] UseIncense = 141,
    [pbr::OriginalName("GET_INCENSE_POKEMON")] GetIncensePokemon = 142,
    [pbr::OriginalName("INCENSE_ENCOUNTER")] IncenseEncounter = 143,
    [pbr::OriginalName("ADD_FORT_MODIFIER")] AddFortModifier = 144,
    [pbr::OriginalName("DISK_ENCOUNTER")] DiskEncounter = 145,
    [pbr::OriginalName("COLLECT_DAILY_DEFENDER_BONUS")] CollectDailyDefenderBonus = 146,
    [pbr::OriginalName("UPGRADE_POKEMON")] UpgradePokemon = 147,
    [pbr::OriginalName("SET_FAVORITE_POKEMON")] SetFavoritePokemon = 148,
    [pbr::OriginalName("NICKNAME_POKEMON")] NicknamePokemon = 149,
    [pbr::OriginalName("EQUIP_BADGE")] EquipBadge = 150,
    [pbr::OriginalName("SET_CONTACT_SETTINGS")] SetContactSettings = 151,
    [pbr::OriginalName("GET_ASSET_DIGEST")] GetAssetDigest = 300,
    [pbr::OriginalName("GET_DOWNLOAD_URLS")] GetDownloadUrls = 301,
    [pbr::OriginalName("GET_SUGGESTED_CODENAMES")] GetSuggestedCodenames = 401,
    [pbr::OriginalName("CHECK_CODENAME_AVAILABLE")] CheckCodenameAvailable = 402,
    [pbr::OriginalName("CLAIM_CODENAME")] ClaimCodename = 403,
    [pbr::OriginalName("SET_AVATAR")] SetAvatar = 404,
    [pbr::OriginalName("SET_PLAYER_TEAM")] SetPlayerTeam = 405,
    [pbr::OriginalName("MARK_TUTORIAL_COMPLETE")] MarkTutorialComplete = 406,
    [pbr::OriginalName("LOAD_SPAWN_POINTS")] LoadSpawnPoints = 500,
    [pbr::OriginalName("ECHO")] Echo = 666,
    [pbr::OriginalName("DEBUG_UPDATE_INVENTORY")] DebugUpdateInventory = 700,
    [pbr::OriginalName("DEBUG_DELETE_PLAYER")] DebugDeletePlayer = 701,
    [pbr::OriginalName("SFIDA_REGISTRATION")] SfidaRegistration = 800,
    [pbr::OriginalName("SFIDA_ACTION_LOG")] SfidaActionLog = 801,
    [pbr::OriginalName("SFIDA_CERTIFICATION")] SfidaCertification = 802,
    [pbr::OriginalName("SFIDA_UPDATE")] SfidaUpdate = 803,
    [pbr::OriginalName("SFIDA_ACTION")] SfidaAction = 804,
    [pbr::OriginalName("SFIDA_DOWSER")] SfidaDowser = 805,
    [pbr::OriginalName("SFIDA_CAPTURE")] SfidaCapture = 806,
  }

  #endregion

}

#endregion Designer generated code
