// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Inventory/AppliedItems.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from Inventory/AppliedItems.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class AppliedItemsReflection {

    #region Descriptor
    /// <summary>File descriptor for Inventory/AppliedItems.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AppliedItemsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxJbnZlbnRvcnkvQXBwbGllZEl0ZW1zLnByb3RvEhRQT0dPUHJvdG9zLklu",
            "dmVudG9yeRobSW52ZW50b3J5L0FwcGxpZWRJdGVtLnByb3RvIj8KDEFwcGxp",
            "ZWRJdGVtcxIvCgRpdGVtGAQgASgLMiEuUE9HT1Byb3Rvcy5JbnZlbnRvcnku",
            "QXBwbGllZEl0ZW1QAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.AppliedItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Inventory.AppliedItems), global::POGOProtos.Inventory.AppliedItems.Parser, new[]{ "Item" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class AppliedItems : pb::IMessage<AppliedItems> {
    private static readonly pb::MessageParser<AppliedItems> _parser = new pb::MessageParser<AppliedItems>(() => new AppliedItems());
    public static pb::MessageParser<AppliedItems> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Inventory.AppliedItemsReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public AppliedItems() {
      OnConstruction();
    }

    partial void OnConstruction();

    public AppliedItems(AppliedItems other) : this() {
      Item = other.item_ != null ? other.Item.Clone() : null;
    }

    public AppliedItems Clone() {
      return new AppliedItems(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 4;
    private global::POGOProtos.Inventory.AppliedItem item_;
    public global::POGOProtos.Inventory.AppliedItem Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as AppliedItems);
    }

    public bool Equals(AppliedItems other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Item, other.Item)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (item_ != null) hash ^= Item.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (item_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Item);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      return size;
    }

    public void MergeFrom(AppliedItems other) {
      if (other == null) {
        return;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          item_ = new global::POGOProtos.Inventory.AppliedItem();
        }
        Item.MergeFrom(other.Item);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 34: {
            if (item_ == null) {
              item_ = new global::POGOProtos.Inventory.AppliedItem();
            }
            input.ReadMessage(item_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
