// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Inventory/InventoryUpgrade.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from Inventory/InventoryUpgrade.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class InventoryUpgradeReflection {

    #region Descriptor
    /// <summary>File descriptor for Inventory/InventoryUpgrade.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InventoryUpgradeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBJbnZlbnRvcnkvSW52ZW50b3J5VXBncmFkZS5wcm90bxIUUE9HT1Byb3Rv",
            "cy5JbnZlbnRvcnkaGEludmVudG9yeS9JdGVtVHlwZS5wcm90bxokSW52ZW50",
            "b3J5L0ludmVudG9yeVVwZ3JhZGVUeXBlLnByb3RvIp4BChBJbnZlbnRvcnlV",
            "cGdyYWRlEiwKBGl0ZW0YASABKA4yHi5QT0dPUHJvdG9zLkludmVudG9yeS5J",
            "dGVtVHlwZRJACgx1cGdyYWRlX3R5cGUYAiABKA4yKi5QT0dPUHJvdG9zLklu",
            "dmVudG9yeS5JbnZlbnRvcnlVcGdyYWRlVHlwZRIaChJhZGRpdGlvbmFsX3N0",
            "b3JhZ2UYAyABKAVQAFABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.ItemTypeReflection.Descriptor, global::POGOProtos.Inventory.InventoryUpgradeTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Inventory.InventoryUpgrade), global::POGOProtos.Inventory.InventoryUpgrade.Parser, new[]{ "Item", "UpgradeType", "AdditionalStorage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class InventoryUpgrade : pb::IMessage<InventoryUpgrade> {
    private static readonly pb::MessageParser<InventoryUpgrade> _parser = new pb::MessageParser<InventoryUpgrade>(() => new InventoryUpgrade());
    public static pb::MessageParser<InventoryUpgrade> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Inventory.InventoryUpgradeReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public InventoryUpgrade() {
      OnConstruction();
    }

    partial void OnConstruction();

    public InventoryUpgrade(InventoryUpgrade other) : this() {
      item_ = other.item_;
      upgradeType_ = other.upgradeType_;
      additionalStorage_ = other.additionalStorage_;
    }

    public InventoryUpgrade Clone() {
      return new InventoryUpgrade(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::POGOProtos.Inventory.ItemType item_ = 0;
    public global::POGOProtos.Inventory.ItemType Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "upgrade_type" field.</summary>
    public const int UpgradeTypeFieldNumber = 2;
    private global::POGOProtos.Inventory.InventoryUpgradeType upgradeType_ = 0;
    public global::POGOProtos.Inventory.InventoryUpgradeType UpgradeType {
      get { return upgradeType_; }
      set {
        upgradeType_ = value;
      }
    }

    /// <summary>Field number for the "additional_storage" field.</summary>
    public const int AdditionalStorageFieldNumber = 3;
    private int additionalStorage_;
    public int AdditionalStorage {
      get { return additionalStorage_; }
      set {
        additionalStorage_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as InventoryUpgrade);
    }

    public bool Equals(InventoryUpgrade other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Item != other.Item) return false;
      if (UpgradeType != other.UpgradeType) return false;
      if (AdditionalStorage != other.AdditionalStorage) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Item != 0) hash ^= Item.GetHashCode();
      if (UpgradeType != 0) hash ^= UpgradeType.GetHashCode();
      if (AdditionalStorage != 0) hash ^= AdditionalStorage.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Item != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Item);
      }
      if (UpgradeType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpgradeType);
      }
      if (AdditionalStorage != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AdditionalStorage);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Item != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Item);
      }
      if (UpgradeType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpgradeType);
      }
      if (AdditionalStorage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AdditionalStorage);
      }
      return size;
    }

    public void MergeFrom(InventoryUpgrade other) {
      if (other == null) {
        return;
      }
      if (other.Item != 0) {
        Item = other.Item;
      }
      if (other.UpgradeType != 0) {
        UpgradeType = other.UpgradeType;
      }
      if (other.AdditionalStorage != 0) {
        AdditionalStorage = other.AdditionalStorage;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            item_ = (global::POGOProtos.Inventory.ItemType) input.ReadEnum();
            break;
          }
          case 16: {
            upgradeType_ = (global::POGOProtos.Inventory.InventoryUpgradeType) input.ReadEnum();
            break;
          }
          case 24: {
            AdditionalStorage = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
