// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Inventory/ItemType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from Inventory/ItemType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ItemTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Inventory/ItemType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhJbnZlbnRvcnkvSXRlbVR5cGUucHJvdG8SFFBPR09Qcm90b3MuSW52ZW50",
            "b3J5KskFCghJdGVtVHlwZRIQCgxJVEVNX1VOS05PV04QABISCg5JVEVNX1BP",
            "S0VfQkFMTBABEhMKD0lURU1fR1JFQVRfQkFMTBACEhMKD0lURU1fVUxUUkFf",
            "QkFMTBADEhQKEElURU1fTUFTVEVSX0JBTEwQBBIPCgtJVEVNX1BPVElPThBl",
            "EhUKEUlURU1fU1VQRVJfUE9USU9OEGYSFQoRSVRFTV9IWVBFUl9QT1RJT04Q",
            "ZxITCg9JVEVNX01BWF9QT1RJT04QaBIQCgtJVEVNX1JFVklWRRDJARIUCg9J",
            "VEVNX01BWF9SRVZJVkUQygESEwoOSVRFTV9MVUNLWV9FR0cQrQISGgoVSVRF",
            "TV9JTkNFTlNFX09SRElOQVJZEJEDEhcKEklURU1fSU5DRU5TRV9TUElDWRCS",
            "AxIWChFJVEVNX0lOQ0VOU0VfQ09PTBCTAxIYChNJVEVNX0lOQ0VOU0VfRkxP",
            "UkFMEJQDEhMKDklURU1fVFJPWV9ESVNLEPUDEhIKDUlURU1fWF9BVFRBQ0sQ",
            "2gQSEwoOSVRFTV9YX0RFRkVOU0UQ2wQSEwoOSVRFTV9YX01JUkFDTEUQ3AQS",
            "FAoPSVRFTV9SQVpaX0JFUlJZEL0FEhQKD0lURU1fQkxVS19CRVJSWRC+BRIV",
            "ChBJVEVNX05BTkFCX0JFUlJZEL8FEhUKEElURU1fV0VQQVJfQkVSUlkQwAUS",
            "FQoQSVRFTV9QSU5BUF9CRVJSWRDBBRIYChNJVEVNX1NQRUNJQUxfQ0FNRVJB",
            "EKEGEiMKHklURU1fSU5DVUJBVE9SX0JBU0lDX1VOTElNSVRFRBCFBxIZChRJ",
            "VEVNX0lOQ1VCQVRPUl9CQVNJQxCGBxIhChxJVEVNX1BPS0VNT05fU1RPUkFH",
            "RV9VUEdSQURFEOkHEh4KGUlURU1fSVRFTV9TVE9SQUdFX1VQR1JBREUQ6gdi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Inventory.ItemType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ItemType {
    [pbr::OriginalName("ITEM_UNKNOWN")] ItemUnknown = 0,
    [pbr::OriginalName("ITEM_POKE_BALL")] ItemPokeBall = 1,
    [pbr::OriginalName("ITEM_GREAT_BALL")] ItemGreatBall = 2,
    [pbr::OriginalName("ITEM_ULTRA_BALL")] ItemUltraBall = 3,
    [pbr::OriginalName("ITEM_MASTER_BALL")] ItemMasterBall = 4,
    [pbr::OriginalName("ITEM_POTION")] ItemPotion = 101,
    [pbr::OriginalName("ITEM_SUPER_POTION")] ItemSuperPotion = 102,
    [pbr::OriginalName("ITEM_HYPER_POTION")] ItemHyperPotion = 103,
    [pbr::OriginalName("ITEM_MAX_POTION")] ItemMaxPotion = 104,
    [pbr::OriginalName("ITEM_REVIVE")] ItemRevive = 201,
    [pbr::OriginalName("ITEM_MAX_REVIVE")] ItemMaxRevive = 202,
    [pbr::OriginalName("ITEM_LUCKY_EGG")] ItemLuckyEgg = 301,
    [pbr::OriginalName("ITEM_INCENSE_ORDINARY")] ItemIncenseOrdinary = 401,
    [pbr::OriginalName("ITEM_INCENSE_SPICY")] ItemIncenseSpicy = 402,
    [pbr::OriginalName("ITEM_INCENSE_COOL")] ItemIncenseCool = 403,
    [pbr::OriginalName("ITEM_INCENSE_FLORAL")] ItemIncenseFloral = 404,
    [pbr::OriginalName("ITEM_TROY_DISK")] ItemTroyDisk = 501,
    [pbr::OriginalName("ITEM_X_ATTACK")] ItemXAttack = 602,
    [pbr::OriginalName("ITEM_X_DEFENSE")] ItemXDefense = 603,
    [pbr::OriginalName("ITEM_X_MIRACLE")] ItemXMiracle = 604,
    [pbr::OriginalName("ITEM_RAZZ_BERRY")] ItemRazzBerry = 701,
    [pbr::OriginalName("ITEM_BLUK_BERRY")] ItemBlukBerry = 702,
    [pbr::OriginalName("ITEM_NANAB_BERRY")] ItemNanabBerry = 703,
    [pbr::OriginalName("ITEM_WEPAR_BERRY")] ItemWeparBerry = 704,
    [pbr::OriginalName("ITEM_PINAP_BERRY")] ItemPinapBerry = 705,
    [pbr::OriginalName("ITEM_SPECIAL_CAMERA")] ItemSpecialCamera = 801,
    [pbr::OriginalName("ITEM_INCUBATOR_BASIC_UNLIMITED")] ItemIncubatorBasicUnlimited = 901,
    [pbr::OriginalName("ITEM_INCUBATOR_BASIC")] ItemIncubatorBasic = 902,
    [pbr::OriginalName("ITEM_POKEMON_STORAGE_UPGRADE")] ItemPokemonStorageUpgrade = 1001,
    [pbr::OriginalName("ITEM_ITEM_STORAGE_UPGRADE")] ItemItemStorageUpgrade = 1002,
  }

  #endregion

}

#endregion Designer generated code
