// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Inventory/PokemonFamily.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Inventory {

  /// <summary>Holder for reflection information generated from Inventory/PokemonFamily.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PokemonFamilyReflection {

    #region Descriptor
    /// <summary>File descriptor for Inventory/PokemonFamily.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PokemonFamilyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1JbnZlbnRvcnkvUG9rZW1vbkZhbWlseS5wcm90bxIUUE9HT1Byb3Rvcy5J",
            "bnZlbnRvcnkaH0ludmVudG9yeS9Qb2tlbW9uRmFtaWx5SWQucHJvdG8iWAoN",
            "UG9rZW1vbkZhbWlseRI4CglmYW1pbHlfaWQYASABKA4yJS5QT0dPUHJvdG9z",
            "LkludmVudG9yeS5Qb2tlbW9uRmFtaWx5SWQSDQoFY2FuZHkYAiABKAVQAGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.PokemonFamilyIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Inventory.PokemonFamily), global::POGOProtos.Inventory.PokemonFamily.Parser, new[]{ "FamilyId", "Candy" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PokemonFamily : pb::IMessage<PokemonFamily> {
    private static readonly pb::MessageParser<PokemonFamily> _parser = new pb::MessageParser<PokemonFamily>(() => new PokemonFamily());
    public static pb::MessageParser<PokemonFamily> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Inventory.PokemonFamilyReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public PokemonFamily() {
      OnConstruction();
    }

    partial void OnConstruction();

    public PokemonFamily(PokemonFamily other) : this() {
      familyId_ = other.familyId_;
      candy_ = other.candy_;
    }

    public PokemonFamily Clone() {
      return new PokemonFamily(this);
    }

    /// <summary>Field number for the "family_id" field.</summary>
    public const int FamilyIdFieldNumber = 1;
    private global::POGOProtos.Inventory.PokemonFamilyId familyId_ = 0;
    public global::POGOProtos.Inventory.PokemonFamilyId FamilyId {
      get { return familyId_; }
      set {
        familyId_ = value;
      }
    }

    /// <summary>Field number for the "candy" field.</summary>
    public const int CandyFieldNumber = 2;
    private int candy_;
    public int Candy {
      get { return candy_; }
      set {
        candy_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as PokemonFamily);
    }

    public bool Equals(PokemonFamily other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FamilyId != other.FamilyId) return false;
      if (Candy != other.Candy) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (FamilyId != 0) hash ^= FamilyId.GetHashCode();
      if (Candy != 0) hash ^= Candy.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (FamilyId != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FamilyId);
      }
      if (Candy != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Candy);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (FamilyId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FamilyId);
      }
      if (Candy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Candy);
      }
      return size;
    }

    public void MergeFrom(PokemonFamily other) {
      if (other == null) {
        return;
      }
      if (other.FamilyId != 0) {
        FamilyId = other.FamilyId;
      }
      if (other.Candy != 0) {
        Candy = other.Candy;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            familyId_ = (global::POGOProtos.Inventory.PokemonFamilyId) input.ReadEnum();
            break;
          }
          case 16: {
            Candy = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
