// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Map/Pokemon/NearbyPokemon.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOLib.Pokemon.Proto.Map.Pokemon {

  /// <summary>Holder for reflection information generated from Map/Pokemon/NearbyPokemon.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class NearbyPokemonReflection {

    #region Descriptor
    /// <summary>File descriptor for Map/Pokemon/NearbyPokemon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NearbyPokemonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9NYXAvUG9rZW1vbi9OZWFyYnlQb2tlbW9uLnByb3RvEiFQT0dPTGliLlBv",
            "a2Vtb24uUHJvdG8uTWFwLlBva2Vtb24aE0VudW1zL1Bva2Vtb24ucHJvdG8i",
            "fQoNTmVhcmJ5UG9rZW1vbhI6Cgxwb2tlbW9uX3R5cGUYASABKA4yJC5QT0dP",
            "TGliLlBva2Vtb24uUHJvdG8uRW51bXMuUG9rZW1vbhIaChJkaXN0YW5jZV9p",
            "bl9tZXRlcnMYAiABKAISFAoMZW5jb3VudGVkX2lkGAMgASgGUABiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOLib.Pokemon.Proto.Enums.PokemonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOLib.Pokemon.Proto.Map.Pokemon.NearbyPokemon), global::POGOLib.Pokemon.Proto.Map.Pokemon.NearbyPokemon.Parser, new[]{ "PokemonType", "DistanceInMeters", "EncountedId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class NearbyPokemon : pb::IMessage<NearbyPokemon> {
    private static readonly pb::MessageParser<NearbyPokemon> _parser = new pb::MessageParser<NearbyPokemon>(() => new NearbyPokemon());
    public static pb::MessageParser<NearbyPokemon> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOLib.Pokemon.Proto.Map.Pokemon.NearbyPokemonReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public NearbyPokemon() {
      OnConstruction();
    }

    partial void OnConstruction();

    public NearbyPokemon(NearbyPokemon other) : this() {
      pokemonType_ = other.pokemonType_;
      distanceInMeters_ = other.distanceInMeters_;
      encountedId_ = other.encountedId_;
    }

    public NearbyPokemon Clone() {
      return new NearbyPokemon(this);
    }

    /// <summary>Field number for the "pokemon_type" field.</summary>
    public const int PokemonTypeFieldNumber = 1;
    private global::POGOLib.Pokemon.Proto.Enums.Pokemon pokemonType_ = 0;
    public global::POGOLib.Pokemon.Proto.Enums.Pokemon PokemonType {
      get { return pokemonType_; }
      set {
        pokemonType_ = value;
      }
    }

    /// <summary>Field number for the "distance_in_meters" field.</summary>
    public const int DistanceInMetersFieldNumber = 2;
    private float distanceInMeters_;
    public float DistanceInMeters {
      get { return distanceInMeters_; }
      set {
        distanceInMeters_ = value;
      }
    }

    /// <summary>Field number for the "encounted_id" field.</summary>
    public const int EncountedIdFieldNumber = 3;
    private ulong encountedId_;
    public ulong EncountedId {
      get { return encountedId_; }
      set {
        encountedId_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as NearbyPokemon);
    }

    public bool Equals(NearbyPokemon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PokemonType != other.PokemonType) return false;
      if (DistanceInMeters != other.DistanceInMeters) return false;
      if (EncountedId != other.EncountedId) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (PokemonType != 0) hash ^= PokemonType.GetHashCode();
      if (DistanceInMeters != 0F) hash ^= DistanceInMeters.GetHashCode();
      if (EncountedId != 0UL) hash ^= EncountedId.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (PokemonType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PokemonType);
      }
      if (DistanceInMeters != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(DistanceInMeters);
      }
      if (EncountedId != 0UL) {
        output.WriteRawTag(25);
        output.WriteFixed64(EncountedId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (PokemonType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PokemonType);
      }
      if (DistanceInMeters != 0F) {
        size += 1 + 4;
      }
      if (EncountedId != 0UL) {
        size += 1 + 8;
      }
      return size;
    }

    public void MergeFrom(NearbyPokemon other) {
      if (other == null) {
        return;
      }
      if (other.PokemonType != 0) {
        PokemonType = other.PokemonType;
      }
      if (other.DistanceInMeters != 0F) {
        DistanceInMeters = other.DistanceInMeters;
      }
      if (other.EncountedId != 0UL) {
        EncountedId = other.EncountedId;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            pokemonType_ = (global::POGOLib.Pokemon.Proto.Enums.Pokemon) input.ReadEnum();
            break;
          }
          case 21: {
            DistanceInMeters = input.ReadFloat();
            break;
          }
          case 25: {
            EncountedId = input.ReadFixed64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
