// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player/PlayerCamera.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Player {

  /// <summary>Holder for reflection information generated from Player/PlayerCamera.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PlayerCameraReflection {

    #region Descriptor
    /// <summary>File descriptor for Player/PlayerCamera.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerCameraReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlQbGF5ZXIvUGxheWVyQ2FtZXJhLnByb3RvEhFQT0dPUHJvdG9zLlBsYXll",
            "ciIpCgxQbGF5ZXJDYW1lcmESGQoRaXNfZGVmYXVsdF9jYW1lcmEYASABKAhi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Player.PlayerCamera), global::POGOProtos.Player.PlayerCamera.Parser, new[]{ "IsDefaultCamera" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PlayerCamera : pb::IMessage<PlayerCamera> {
    private static readonly pb::MessageParser<PlayerCamera> _parser = new pb::MessageParser<PlayerCamera>(() => new PlayerCamera());
    public static pb::MessageParser<PlayerCamera> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Player.PlayerCameraReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public PlayerCamera() {
      OnConstruction();
    }

    partial void OnConstruction();

    public PlayerCamera(PlayerCamera other) : this() {
      isDefaultCamera_ = other.isDefaultCamera_;
    }

    public PlayerCamera Clone() {
      return new PlayerCamera(this);
    }

    /// <summary>Field number for the "is_default_camera" field.</summary>
    public const int IsDefaultCameraFieldNumber = 1;
    private bool isDefaultCamera_;
    public bool IsDefaultCamera {
      get { return isDefaultCamera_; }
      set {
        isDefaultCamera_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as PlayerCamera);
    }

    public bool Equals(PlayerCamera other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsDefaultCamera != other.IsDefaultCamera) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (IsDefaultCamera != false) hash ^= IsDefaultCamera.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (IsDefaultCamera != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsDefaultCamera);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (IsDefaultCamera != false) {
        size += 1 + 1;
      }
      return size;
    }

    public void MergeFrom(PlayerCamera other) {
      if (other == null) {
        return;
      }
      if (other.IsDefaultCamera != false) {
        IsDefaultCamera = other.IsDefaultCamera;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            IsDefaultCamera = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
