// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Networking/Responses/GetPlayerResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from Networking/Responses/GetPlayerResponse.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class GetPlayerResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for Networking/Responses/GetPlayerResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetPlayerResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixOZXR3b3JraW5nL1Jlc3BvbnNlcy9HZXRQbGF5ZXJSZXNwb25zZS5wcm90",
            "bxIfUE9HT1Byb3Rvcy5OZXR3b3JraW5nLlJlc3BvbnNlcxoRTG9jYWxQbGF5",
            "ZXIucHJvdG8iVAoRR2V0UGxheWVyUmVzcG9uc2USEAoIdW5rbm93bjEYASAB",
            "KA0SLQoMbG9jYWxfcGxheWVyGAIgASgLMhcuUE9HT1Byb3Rvcy5Mb2NhbFBs",
            "YXllclAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.LocalPlayerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.GetPlayerResponse), global::POGOProtos.Networking.Responses.GetPlayerResponse.Parser, new[]{ "Unknown1", "LocalPlayer" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetPlayerResponse : pb::IMessage<GetPlayerResponse> {
    private static readonly pb::MessageParser<GetPlayerResponse> _parser = new pb::MessageParser<GetPlayerResponse>(() => new GetPlayerResponse());
    public static pb::MessageParser<GetPlayerResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.GetPlayerResponseReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetPlayerResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetPlayerResponse(GetPlayerResponse other) : this() {
      unknown1_ = other.unknown1_;
      LocalPlayer = other.localPlayer_ != null ? other.LocalPlayer.Clone() : null;
    }

    public GetPlayerResponse Clone() {
      return new GetPlayerResponse(this);
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 1;
    private uint unknown1_;
    public uint Unknown1 {
      get { return unknown1_; }
      set {
        unknown1_ = value;
      }
    }

    /// <summary>Field number for the "local_player" field.</summary>
    public const int LocalPlayerFieldNumber = 2;
    private global::POGOProtos.LocalPlayer localPlayer_;
    public global::POGOProtos.LocalPlayer LocalPlayer {
      get { return localPlayer_; }
      set {
        localPlayer_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetPlayerResponse);
    }

    public bool Equals(GetPlayerResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unknown1 != other.Unknown1) return false;
      if (!object.Equals(LocalPlayer, other.LocalPlayer)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
      if (localPlayer_ != null) hash ^= LocalPlayer.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Unknown1 != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Unknown1);
      }
      if (localPlayer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LocalPlayer);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Unknown1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unknown1);
      }
      if (localPlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalPlayer);
      }
      return size;
    }

    public void MergeFrom(GetPlayerResponse other) {
      if (other == null) {
        return;
      }
      if (other.Unknown1 != 0) {
        Unknown1 = other.Unknown1;
      }
      if (other.localPlayer_ != null) {
        if (localPlayer_ == null) {
          localPlayer_ = new global::POGOProtos.LocalPlayer();
        }
        LocalPlayer.MergeFrom(other.LocalPlayer);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Unknown1 = input.ReadUInt32();
            break;
          }
          case 18: {
            if (localPlayer_ == null) {
              localPlayer_ = new global::POGOProtos.LocalPlayer();
            }
            input.ReadMessage(localPlayer_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
