// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Map/Fort/FortRenderingType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOLib.Pokemon.Proto.Map.Fort {

  /// <summary>Holder for reflection information generated from Map/Fort/FortRenderingType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class FortRenderingTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Map/Fort/FortRenderingType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FortRenderingTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBNYXAvRm9ydC9Gb3J0UmVuZGVyaW5nVHlwZS5wcm90bxIeUE9HT0xpYi5Q",
            "b2tlbW9uLlByb3RvLk1hcC5Gb3J0KjMKEUZvcnRSZW5kZXJpbmdUeXBlEgsK",
            "B0RFRkFVTFQQABIRCg1JTlRFUk5BTF9URVNUEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOLib.Pokemon.Proto.Map.Fort.FortRenderingType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum FortRenderingType {
    [pbr::OriginalName("DEFAULT")] Default = 0,
    [pbr::OriginalName("INTERNAL_TEST")] InternalTest = 1,
  }

  #endregion

}

#endregion Designer generated code
