// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocalPlayer.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOLib.Pokemon.Proto {

  /// <summary>Holder for reflection information generated from LocalPlayer.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class LocalPlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for LocalPlayer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LocalPlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMb2NhbFBsYXllci5wcm90bxIVUE9HT0xpYi5Qb2tlbW9uLlByb3RvGhpQ",
            "bGF5ZXIvQXZhdGFyRGV0YWlscy5wcm90bxoXUGxheWVyL0RhaWx5Qm9udXMu",
            "cHJvdG8aGlBsYXllci9FcXVpcHBlZEJhZGdlLnByb3RvGhxQbGF5ZXIvQ29u",
            "dGFjdFNldHRpbmdzLnByb3RvGhVQbGF5ZXIvQ3VycmVuY3kucHJvdG8i7AMK",
            "C0xvY2FsUGxheWVyEh0KFWNyZWF0aW9uX3RpbWVzdGFtcF9tcxgBIAEoAxIQ",
            "Cgh1c2VybmFtZRgCIAEoCRIMCgR0ZWFtGAUgASgFEhkKEXR1dG9yaWFsX2Nv",
            "bXBsZXRlGAcgASgMEkMKDmF2YXRhcl9kZXRhaWxzGAggASgLMisuUE9HT0xp",
            "Yi5Qb2tlbW9uLlByb3RvLlBsYXllci5BdmF0YXJEZXRhaWxzEhsKE21heF9w",
            "b2tlbW9uX3N0b3JhZ2UYCSABKAUSGAoQbWF4X2l0ZW1fc3RvcmFnZRgKIAEo",
            "BRI9CgtkYWlseV9ib251cxgLIAEoCzIoLlBPR09MaWIuUG9rZW1vbi5Qcm90",
            "by5QbGF5ZXIuRGFpbHlCb251cxJDCg5lcXVpcHBlZF9iYWRnZRgMIAEoCzIr",
            "LlBPR09MaWIuUG9rZW1vbi5Qcm90by5QbGF5ZXIuRXF1aXBwZWRCYWRnZRJH",
            "ChBjb250YWN0X3NldHRpbmdzGA0gASgLMi0uUE9HT0xpYi5Qb2tlbW9uLlBy",
            "b3RvLlBsYXllci5Db250YWN0U2V0dGluZ3MSOgoKY3VycmVuY2llcxgOIAMo",
            "CzImLlBPR09MaWIuUG9rZW1vbi5Qcm90by5QbGF5ZXIuQ3VycmVuY3lQAFAB",
            "UAJQA1AEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOLib.Pokemon.Proto.Player.AvatarDetailsReflection.Descriptor, global::POGOLib.Pokemon.Proto.Player.DailyBonusReflection.Descriptor, global::POGOLib.Pokemon.Proto.Player.EquippedBadgeReflection.Descriptor, global::POGOLib.Pokemon.Proto.Player.ContactSettingsReflection.Descriptor, global::POGOLib.Pokemon.Proto.Player.CurrencyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOLib.Pokemon.Proto.LocalPlayer), global::POGOLib.Pokemon.Proto.LocalPlayer.Parser, new[]{ "CreationTimestampMs", "Username", "Team", "TutorialComplete", "AvatarDetails", "MaxPokemonStorage", "MaxItemStorage", "DailyBonus", "EquippedBadge", "ContactSettings", "Currencies" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LocalPlayer : pb::IMessage<LocalPlayer> {
    private static readonly pb::MessageParser<LocalPlayer> _parser = new pb::MessageParser<LocalPlayer>(() => new LocalPlayer());
    public static pb::MessageParser<LocalPlayer> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOLib.Pokemon.Proto.LocalPlayerReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public LocalPlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    public LocalPlayer(LocalPlayer other) : this() {
      creationTimestampMs_ = other.creationTimestampMs_;
      username_ = other.username_;
      team_ = other.team_;
      tutorialComplete_ = other.tutorialComplete_;
      AvatarDetails = other.avatarDetails_ != null ? other.AvatarDetails.Clone() : null;
      maxPokemonStorage_ = other.maxPokemonStorage_;
      maxItemStorage_ = other.maxItemStorage_;
      DailyBonus = other.dailyBonus_ != null ? other.DailyBonus.Clone() : null;
      EquippedBadge = other.equippedBadge_ != null ? other.EquippedBadge.Clone() : null;
      ContactSettings = other.contactSettings_ != null ? other.ContactSettings.Clone() : null;
      currencies_ = other.currencies_.Clone();
    }

    public LocalPlayer Clone() {
      return new LocalPlayer(this);
    }

    /// <summary>Field number for the "creation_timestamp_ms" field.</summary>
    public const int CreationTimestampMsFieldNumber = 1;
    private long creationTimestampMs_;
    public long CreationTimestampMs {
      get { return creationTimestampMs_; }
      set {
        creationTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "team" field.</summary>
    public const int TeamFieldNumber = 5;
    private int team_;
    public int Team {
      get { return team_; }
      set {
        team_ = value;
      }
    }

    /// <summary>Field number for the "tutorial_complete" field.</summary>
    public const int TutorialCompleteFieldNumber = 7;
    private pb::ByteString tutorialComplete_ = pb::ByteString.Empty;
    public pb::ByteString TutorialComplete {
      get { return tutorialComplete_; }
      set {
        tutorialComplete_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_details" field.</summary>
    public const int AvatarDetailsFieldNumber = 8;
    private global::POGOLib.Pokemon.Proto.Player.AvatarDetails avatarDetails_;
    public global::POGOLib.Pokemon.Proto.Player.AvatarDetails AvatarDetails {
      get { return avatarDetails_; }
      set {
        avatarDetails_ = value;
      }
    }

    /// <summary>Field number for the "max_pokemon_storage" field.</summary>
    public const int MaxPokemonStorageFieldNumber = 9;
    private int maxPokemonStorage_;
    public int MaxPokemonStorage {
      get { return maxPokemonStorage_; }
      set {
        maxPokemonStorage_ = value;
      }
    }

    /// <summary>Field number for the "max_item_storage" field.</summary>
    public const int MaxItemStorageFieldNumber = 10;
    private int maxItemStorage_;
    public int MaxItemStorage {
      get { return maxItemStorage_; }
      set {
        maxItemStorage_ = value;
      }
    }

    /// <summary>Field number for the "daily_bonus" field.</summary>
    public const int DailyBonusFieldNumber = 11;
    private global::POGOLib.Pokemon.Proto.Player.DailyBonus dailyBonus_;
    public global::POGOLib.Pokemon.Proto.Player.DailyBonus DailyBonus {
      get { return dailyBonus_; }
      set {
        dailyBonus_ = value;
      }
    }

    /// <summary>Field number for the "equipped_badge" field.</summary>
    public const int EquippedBadgeFieldNumber = 12;
    private global::POGOLib.Pokemon.Proto.Player.EquippedBadge equippedBadge_;
    public global::POGOLib.Pokemon.Proto.Player.EquippedBadge EquippedBadge {
      get { return equippedBadge_; }
      set {
        equippedBadge_ = value;
      }
    }

    /// <summary>Field number for the "contact_settings" field.</summary>
    public const int ContactSettingsFieldNumber = 13;
    private global::POGOLib.Pokemon.Proto.Player.ContactSettings contactSettings_;
    public global::POGOLib.Pokemon.Proto.Player.ContactSettings ContactSettings {
      get { return contactSettings_; }
      set {
        contactSettings_ = value;
      }
    }

    /// <summary>Field number for the "currencies" field.</summary>
    public const int CurrenciesFieldNumber = 14;
    private static readonly pb::FieldCodec<global::POGOLib.Pokemon.Proto.Player.Currency> _repeated_currencies_codec
        = pb::FieldCodec.ForMessage(114, global::POGOLib.Pokemon.Proto.Player.Currency.Parser);
    private readonly pbc::RepeatedField<global::POGOLib.Pokemon.Proto.Player.Currency> currencies_ = new pbc::RepeatedField<global::POGOLib.Pokemon.Proto.Player.Currency>();
    public pbc::RepeatedField<global::POGOLib.Pokemon.Proto.Player.Currency> Currencies {
      get { return currencies_; }
    }

    public override bool Equals(object other) {
      return Equals(other as LocalPlayer);
    }

    public bool Equals(LocalPlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CreationTimestampMs != other.CreationTimestampMs) return false;
      if (Username != other.Username) return false;
      if (Team != other.Team) return false;
      if (TutorialComplete != other.TutorialComplete) return false;
      if (!object.Equals(AvatarDetails, other.AvatarDetails)) return false;
      if (MaxPokemonStorage != other.MaxPokemonStorage) return false;
      if (MaxItemStorage != other.MaxItemStorage) return false;
      if (!object.Equals(DailyBonus, other.DailyBonus)) return false;
      if (!object.Equals(EquippedBadge, other.EquippedBadge)) return false;
      if (!object.Equals(ContactSettings, other.ContactSettings)) return false;
      if(!currencies_.Equals(other.currencies_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (CreationTimestampMs != 0L) hash ^= CreationTimestampMs.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Team != 0) hash ^= Team.GetHashCode();
      if (TutorialComplete.Length != 0) hash ^= TutorialComplete.GetHashCode();
      if (avatarDetails_ != null) hash ^= AvatarDetails.GetHashCode();
      if (MaxPokemonStorage != 0) hash ^= MaxPokemonStorage.GetHashCode();
      if (MaxItemStorage != 0) hash ^= MaxItemStorage.GetHashCode();
      if (dailyBonus_ != null) hash ^= DailyBonus.GetHashCode();
      if (equippedBadge_ != null) hash ^= EquippedBadge.GetHashCode();
      if (contactSettings_ != null) hash ^= ContactSettings.GetHashCode();
      hash ^= currencies_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (CreationTimestampMs != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CreationTimestampMs);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Team != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Team);
      }
      if (TutorialComplete.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(TutorialComplete);
      }
      if (avatarDetails_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(AvatarDetails);
      }
      if (MaxPokemonStorage != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MaxPokemonStorage);
      }
      if (MaxItemStorage != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(MaxItemStorage);
      }
      if (dailyBonus_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DailyBonus);
      }
      if (equippedBadge_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(EquippedBadge);
      }
      if (contactSettings_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(ContactSettings);
      }
      currencies_.WriteTo(output, _repeated_currencies_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (CreationTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreationTimestampMs);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Team != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Team);
      }
      if (TutorialComplete.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TutorialComplete);
      }
      if (avatarDetails_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarDetails);
      }
      if (MaxPokemonStorage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPokemonStorage);
      }
      if (MaxItemStorage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxItemStorage);
      }
      if (dailyBonus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DailyBonus);
      }
      if (equippedBadge_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EquippedBadge);
      }
      if (contactSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContactSettings);
      }
      size += currencies_.CalculateSize(_repeated_currencies_codec);
      return size;
    }

    public void MergeFrom(LocalPlayer other) {
      if (other == null) {
        return;
      }
      if (other.CreationTimestampMs != 0L) {
        CreationTimestampMs = other.CreationTimestampMs;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Team != 0) {
        Team = other.Team;
      }
      if (other.TutorialComplete.Length != 0) {
        TutorialComplete = other.TutorialComplete;
      }
      if (other.avatarDetails_ != null) {
        if (avatarDetails_ == null) {
          avatarDetails_ = new global::POGOLib.Pokemon.Proto.Player.AvatarDetails();
        }
        AvatarDetails.MergeFrom(other.AvatarDetails);
      }
      if (other.MaxPokemonStorage != 0) {
        MaxPokemonStorage = other.MaxPokemonStorage;
      }
      if (other.MaxItemStorage != 0) {
        MaxItemStorage = other.MaxItemStorage;
      }
      if (other.dailyBonus_ != null) {
        if (dailyBonus_ == null) {
          dailyBonus_ = new global::POGOLib.Pokemon.Proto.Player.DailyBonus();
        }
        DailyBonus.MergeFrom(other.DailyBonus);
      }
      if (other.equippedBadge_ != null) {
        if (equippedBadge_ == null) {
          equippedBadge_ = new global::POGOLib.Pokemon.Proto.Player.EquippedBadge();
        }
        EquippedBadge.MergeFrom(other.EquippedBadge);
      }
      if (other.contactSettings_ != null) {
        if (contactSettings_ == null) {
          contactSettings_ = new global::POGOLib.Pokemon.Proto.Player.ContactSettings();
        }
        ContactSettings.MergeFrom(other.ContactSettings);
      }
      currencies_.Add(other.currencies_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            CreationTimestampMs = input.ReadInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 40: {
            Team = input.ReadInt32();
            break;
          }
          case 58: {
            TutorialComplete = input.ReadBytes();
            break;
          }
          case 66: {
            if (avatarDetails_ == null) {
              avatarDetails_ = new global::POGOLib.Pokemon.Proto.Player.AvatarDetails();
            }
            input.ReadMessage(avatarDetails_);
            break;
          }
          case 72: {
            MaxPokemonStorage = input.ReadInt32();
            break;
          }
          case 80: {
            MaxItemStorage = input.ReadInt32();
            break;
          }
          case 90: {
            if (dailyBonus_ == null) {
              dailyBonus_ = new global::POGOLib.Pokemon.Proto.Player.DailyBonus();
            }
            input.ReadMessage(dailyBonus_);
            break;
          }
          case 98: {
            if (equippedBadge_ == null) {
              equippedBadge_ = new global::POGOLib.Pokemon.Proto.Player.EquippedBadge();
            }
            input.ReadMessage(equippedBadge_);
            break;
          }
          case 106: {
            if (contactSettings_ == null) {
              contactSettings_ = new global::POGOLib.Pokemon.Proto.Player.ContactSettings();
            }
            input.ReadMessage(contactSettings_);
            break;
          }
          case 114: {
            currencies_.AddEntriesFrom(input, _repeated_currencies_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
