// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapObjects.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOLib.Pokemon.Proto {

  /// <summary>Holder for reflection information generated from MapObjects.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class MapObjectsReflection {

    #region Descriptor
    /// <summary>File descriptor for MapObjects.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapObjectsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBNYXBPYmplY3RzLnByb3RvEhVQT0dPTGliLlBva2Vtb24uUHJvdG8aEU1h",
            "cC9NYXBDZWxsLnByb3RvGhpNYXAvTWFwT2JqZWN0c1N0YXR1cy5wcm90byKA",
            "AQoKTWFwT2JqZWN0cxI1CgltYXBfY2VsbHMYASADKAsyIi5QT0dPTGliLlBv",
            "a2Vtb24uUHJvdG8uTWFwLk1hcENlbGwSOwoGc3RhdHVzGAIgASgOMisuUE9H",
            "T0xpYi5Qb2tlbW9uLlByb3RvLk1hcC5NYXBPYmplY3RzU3RhdHVzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOLib.Pokemon.Proto.Map.MapCellReflection.Descriptor, global::POGOLib.Pokemon.Proto.Map.MapObjectsStatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOLib.Pokemon.Proto.MapObjects), global::POGOLib.Pokemon.Proto.MapObjects.Parser, new[]{ "MapCells", "Status" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class MapObjects : pb::IMessage<MapObjects> {
    private static readonly pb::MessageParser<MapObjects> _parser = new pb::MessageParser<MapObjects>(() => new MapObjects());
    public static pb::MessageParser<MapObjects> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOLib.Pokemon.Proto.MapObjectsReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public MapObjects() {
      OnConstruction();
    }

    partial void OnConstruction();

    public MapObjects(MapObjects other) : this() {
      mapCells_ = other.mapCells_.Clone();
      status_ = other.status_;
    }

    public MapObjects Clone() {
      return new MapObjects(this);
    }

    /// <summary>Field number for the "map_cells" field.</summary>
    public const int MapCellsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::POGOLib.Pokemon.Proto.Map.MapCell> _repeated_mapCells_codec
        = pb::FieldCodec.ForMessage(10, global::POGOLib.Pokemon.Proto.Map.MapCell.Parser);
    private readonly pbc::RepeatedField<global::POGOLib.Pokemon.Proto.Map.MapCell> mapCells_ = new pbc::RepeatedField<global::POGOLib.Pokemon.Proto.Map.MapCell>();
    public pbc::RepeatedField<global::POGOLib.Pokemon.Proto.Map.MapCell> MapCells {
      get { return mapCells_; }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::POGOLib.Pokemon.Proto.Map.MapObjectsStatus status_ = 0;
    public global::POGOLib.Pokemon.Proto.Map.MapObjectsStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as MapObjects);
    }

    public bool Equals(MapObjects other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mapCells_.Equals(other.mapCells_)) return false;
      if (Status != other.Status) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= mapCells_.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      mapCells_.WriteTo(output, _repeated_mapCells_codec);
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
    }

    public int CalculateSize() {
      int size = 0;
      size += mapCells_.CalculateSize(_repeated_mapCells_codec);
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      return size;
    }

    public void MergeFrom(MapObjects other) {
      if (other == null) {
        return;
      }
      mapCells_.Add(other.mapCells_);
      if (other.Status != 0) {
        Status = other.Status;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            mapCells_.AddEntriesFrom(input, _repeated_mapCells_codec);
            break;
          }
          case 16: {
            status_ = (global::POGOLib.Pokemon.Proto.Map.MapObjectsStatus) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
