// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums/Envelopes/Direction.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums.Envelopes {

  /// <summary>Holder for reflection information generated from Enums/Envelopes/Direction.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class DirectionReflection {

    #region Descriptor
    /// <summary>File descriptor for Enums/Envelopes/Direction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DirectionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9FbnVtcy9FbnZlbG9wZXMvRGlyZWN0aW9uLnByb3RvEhpQT0dPUHJvdG9z",
            "LkVudW1zLkVudmVsb3BlcyozCglEaXJlY3Rpb24SCwoHVU5LTk9XThAAEgwK",
            "CFJFU1BPTlNFEAESCwoHUkVRVUVTVBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.Envelopes.Direction), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Direction {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("RESPONSE")] Response = 1,
    [pbr::OriginalName("REQUEST")] Request = 2,
  }

  #endregion

}

#endregion Designer generated code
