// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Networking/Requests/Messages/GetMapObjectsMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from Networking/Requests/Messages/GetMapObjectsMessage.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class GetMapObjectsMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Networking/Requests/Messages/GetMapObjectsMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetMapObjectsMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjdOZXR3b3JraW5nL1JlcXVlc3RzL01lc3NhZ2VzL0dldE1hcE9iamVjdHNN",
            "ZXNzYWdlLnByb3RvEidQT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVxdWVzdHMu",
            "TWVzc2FnZXMicAoUR2V0TWFwT2JqZWN0c01lc3NhZ2USEwoHY2VsbF9pZBgB",
            "IAMoBEICEAESHgoSc2luY2VfdGltZXN0YW1wX21zGAIgAygDQgIQARIQCghs",
            "YXRpdHVkZRgDIAEoARIRCglsb25naXR1ZGUYBCABKAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage), global::POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage.Parser, new[]{ "CellId", "SinceTimestampMs", "Latitude", "Longitude" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetMapObjectsMessage : pb::IMessage<GetMapObjectsMessage> {
    private static readonly pb::MessageParser<GetMapObjectsMessage> _parser = new pb::MessageParser<GetMapObjectsMessage>(() => new GetMapObjectsMessage());
    public static pb::MessageParser<GetMapObjectsMessage> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Requests.Messages.GetMapObjectsMessageReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetMapObjectsMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetMapObjectsMessage(GetMapObjectsMessage other) : this() {
      cellId_ = other.cellId_.Clone();
      sinceTimestampMs_ = other.sinceTimestampMs_.Clone();
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
    }

    public GetMapObjectsMessage Clone() {
      return new GetMapObjectsMessage(this);
    }

    /// <summary>Field number for the "cell_id" field.</summary>
    public const int CellIdFieldNumber = 1;
    private static readonly pb::FieldCodec<ulong> _repeated_cellId_codec
        = pb::FieldCodec.ForUInt64(10);
    private readonly pbc::RepeatedField<ulong> cellId_ = new pbc::RepeatedField<ulong>();
    public pbc::RepeatedField<ulong> CellId {
      get { return cellId_; }
    }

    /// <summary>Field number for the "since_timestamp_ms" field.</summary>
    public const int SinceTimestampMsFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_sinceTimestampMs_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> sinceTimestampMs_ = new pbc::RepeatedField<long>();
    public pbc::RepeatedField<long> SinceTimestampMs {
      get { return sinceTimestampMs_; }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 3;
    private double latitude_;
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 4;
    private double longitude_;
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetMapObjectsMessage);
    }

    public bool Equals(GetMapObjectsMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!cellId_.Equals(other.cellId_)) return false;
      if(!sinceTimestampMs_.Equals(other.sinceTimestampMs_)) return false;
      if (Latitude != other.Latitude) return false;
      if (Longitude != other.Longitude) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= cellId_.GetHashCode();
      hash ^= sinceTimestampMs_.GetHashCode();
      if (Latitude != 0D) hash ^= Latitude.GetHashCode();
      if (Longitude != 0D) hash ^= Longitude.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      cellId_.WriteTo(output, _repeated_cellId_codec);
      sinceTimestampMs_.WriteTo(output, _repeated_sinceTimestampMs_codec);
      if (Latitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Longitude);
      }
    }

    public int CalculateSize() {
      int size = 0;
      size += cellId_.CalculateSize(_repeated_cellId_codec);
      size += sinceTimestampMs_.CalculateSize(_repeated_sinceTimestampMs_codec);
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      return size;
    }

    public void MergeFrom(GetMapObjectsMessage other) {
      if (other == null) {
        return;
      }
      cellId_.Add(other.cellId_);
      sinceTimestampMs_.Add(other.sinceTimestampMs_);
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            cellId_.AddEntriesFrom(input, _repeated_cellId_codec);
            break;
          }
          case 18:
          case 16: {
            sinceTimestampMs_.AddEntriesFrom(input, _repeated_sinceTimestampMs_codec);
            break;
          }
          case 25: {
            Latitude = input.ReadDouble();
            break;
          }
          case 33: {
            Longitude = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
