// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Settings/GlobalSettings.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings {

  /// <summary>Holder for reflection information generated from Settings/GlobalSettings.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class GlobalSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for Settings/GlobalSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GlobalSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1TZXR0aW5ncy9HbG9iYWxTZXR0aW5ncy5wcm90bxITUE9HT1Byb3Rvcy5T",
            "ZXR0aW5ncxoTU2V0dGluZ3MvRm9ydC5wcm90bxoSU2V0dGluZ3MvTWFwLnBy",
            "b3RvGhRTZXR0aW5ncy9MZXZlbC5wcm90bxoYU2V0dGluZ3MvSW52ZW50b3J5",
            "LnByb3RvIt4BCg5HbG9iYWxTZXR0aW5ncxInCgRmb3J0GAIgASgLMhkuUE9H",
            "T1Byb3Rvcy5TZXR0aW5ncy5Gb3J0EiUKA21hcBgDIAEoCzIYLlBPR09Qcm90",
            "b3MuU2V0dGluZ3MuTWFwEikKBWxldmVsGAQgASgLMhouUE9HT1Byb3Rvcy5T",
            "ZXR0aW5ncy5MZXZlbBIxCglpbnZlbnRvcnkYBSABKAsyHi5QT0dPUHJvdG9z",
            "LlNldHRpbmdzLkludmVudG9yeRIeChZtaW5pbXVtX2NsaWVudF92ZXJzaW9u",
            "GAYgASgJUABQAVACUANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Settings.FortReflection.Descriptor, global::POGOProtos.Settings.MapReflection.Descriptor, global::POGOProtos.Settings.LevelReflection.Descriptor, global::POGOProtos.Settings.InventoryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.GlobalSettings), global::POGOProtos.Settings.GlobalSettings.Parser, new[]{ "Fort", "Map", "Level", "Inventory", "MinimumClientVersion" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GlobalSettings : pb::IMessage<GlobalSettings> {
    private static readonly pb::MessageParser<GlobalSettings> _parser = new pb::MessageParser<GlobalSettings>(() => new GlobalSettings());
    public static pb::MessageParser<GlobalSettings> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.GlobalSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GlobalSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GlobalSettings(GlobalSettings other) : this() {
      Fort = other.fort_ != null ? other.Fort.Clone() : null;
      Map = other.map_ != null ? other.Map.Clone() : null;
      Level = other.level_ != null ? other.Level.Clone() : null;
      Inventory = other.inventory_ != null ? other.Inventory.Clone() : null;
      minimumClientVersion_ = other.minimumClientVersion_;
    }

    public GlobalSettings Clone() {
      return new GlobalSettings(this);
    }

    /// <summary>Field number for the "fort" field.</summary>
    public const int FortFieldNumber = 2;
    private global::POGOProtos.Settings.Fort fort_;
    public global::POGOProtos.Settings.Fort Fort {
      get { return fort_; }
      set {
        fort_ = value;
      }
    }

    /// <summary>Field number for the "map" field.</summary>
    public const int MapFieldNumber = 3;
    private global::POGOProtos.Settings.Map map_;
    public global::POGOProtos.Settings.Map Map {
      get { return map_; }
      set {
        map_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 4;
    private global::POGOProtos.Settings.Level level_;
    public global::POGOProtos.Settings.Level Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "inventory" field.</summary>
    public const int InventoryFieldNumber = 5;
    private global::POGOProtos.Settings.Inventory inventory_;
    public global::POGOProtos.Settings.Inventory Inventory {
      get { return inventory_; }
      set {
        inventory_ = value;
      }
    }

    /// <summary>Field number for the "minimum_client_version" field.</summary>
    public const int MinimumClientVersionFieldNumber = 6;
    private string minimumClientVersion_ = "";
    public string MinimumClientVersion {
      get { return minimumClientVersion_; }
      set {
        minimumClientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GlobalSettings);
    }

    public bool Equals(GlobalSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Fort, other.Fort)) return false;
      if (!object.Equals(Map, other.Map)) return false;
      if (!object.Equals(Level, other.Level)) return false;
      if (!object.Equals(Inventory, other.Inventory)) return false;
      if (MinimumClientVersion != other.MinimumClientVersion) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (fort_ != null) hash ^= Fort.GetHashCode();
      if (map_ != null) hash ^= Map.GetHashCode();
      if (level_ != null) hash ^= Level.GetHashCode();
      if (inventory_ != null) hash ^= Inventory.GetHashCode();
      if (MinimumClientVersion.Length != 0) hash ^= MinimumClientVersion.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (fort_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Fort);
      }
      if (map_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Map);
      }
      if (level_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Level);
      }
      if (inventory_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Inventory);
      }
      if (MinimumClientVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MinimumClientVersion);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (fort_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Fort);
      }
      if (map_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Map);
      }
      if (level_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Level);
      }
      if (inventory_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Inventory);
      }
      if (MinimumClientVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MinimumClientVersion);
      }
      return size;
    }

    public void MergeFrom(GlobalSettings other) {
      if (other == null) {
        return;
      }
      if (other.fort_ != null) {
        if (fort_ == null) {
          fort_ = new global::POGOProtos.Settings.Fort();
        }
        Fort.MergeFrom(other.Fort);
      }
      if (other.map_ != null) {
        if (map_ == null) {
          map_ = new global::POGOProtos.Settings.Map();
        }
        Map.MergeFrom(other.Map);
      }
      if (other.level_ != null) {
        if (level_ == null) {
          level_ = new global::POGOProtos.Settings.Level();
        }
        Level.MergeFrom(other.Level);
      }
      if (other.inventory_ != null) {
        if (inventory_ == null) {
          inventory_ = new global::POGOProtos.Settings.Inventory();
        }
        Inventory.MergeFrom(other.Inventory);
      }
      if (other.MinimumClientVersion.Length != 0) {
        MinimumClientVersion = other.MinimumClientVersion;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            if (fort_ == null) {
              fort_ = new global::POGOProtos.Settings.Fort();
            }
            input.ReadMessage(fort_);
            break;
          }
          case 26: {
            if (map_ == null) {
              map_ = new global::POGOProtos.Settings.Map();
            }
            input.ReadMessage(map_);
            break;
          }
          case 34: {
            if (level_ == null) {
              level_ = new global::POGOProtos.Settings.Level();
            }
            input.ReadMessage(level_);
            break;
          }
          case 42: {
            if (inventory_ == null) {
              inventory_ = new global::POGOProtos.Settings.Inventory();
            }
            input.ReadMessage(inventory_);
            break;
          }
          case 50: {
            MinimumClientVersion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
