// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Requests/Messages/GetInventoryMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Requests.Messages {

  /// <summary>Holder for reflection information generated from Requests/Messages/GetInventoryMessage.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class GetInventoryMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Requests/Messages/GetInventoryMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetInventoryMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitSZXF1ZXN0cy9NZXNzYWdlcy9HZXRJbnZlbnRvcnlNZXNzYWdlLnByb3Rv",
            "EhxQT0dPUHJvdG9zLlJlcXVlc3RzLk1lc3NhZ2VzIkMKE0dldEludmVudG9y",
            "eU1lc3NhZ2USFAoMdGltZXN0YW1wX21zGAEgASgDEhYKDml0ZW1fYmVlbl9z",
            "ZWVuGAIgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Requests.Messages.GetInventoryMessage), global::POGOProtos.Requests.Messages.GetInventoryMessage.Parser, new[]{ "TimestampMs", "ItemBeenSeen" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GetInventoryMessage : pb::IMessage<GetInventoryMessage> {
    private static readonly pb::MessageParser<GetInventoryMessage> _parser = new pb::MessageParser<GetInventoryMessage>(() => new GetInventoryMessage());
    public static pb::MessageParser<GetInventoryMessage> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Requests.Messages.GetInventoryMessageReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GetInventoryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GetInventoryMessage(GetInventoryMessage other) : this() {
      timestampMs_ = other.timestampMs_;
      itemBeenSeen_ = other.itemBeenSeen_;
    }

    public GetInventoryMessage Clone() {
      return new GetInventoryMessage(this);
    }

    /// <summary>Field number for the "timestamp_ms" field.</summary>
    public const int TimestampMsFieldNumber = 1;
    private long timestampMs_;
    public long TimestampMs {
      get { return timestampMs_; }
      set {
        timestampMs_ = value;
      }
    }

    /// <summary>Field number for the "item_been_seen" field.</summary>
    public const int ItemBeenSeenFieldNumber = 2;
    private int itemBeenSeen_;
    /// <summary>
    ///  TODO: Find out what this is.
    /// </summary>
    public int ItemBeenSeen {
      get { return itemBeenSeen_; }
      set {
        itemBeenSeen_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GetInventoryMessage);
    }

    public bool Equals(GetInventoryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimestampMs != other.TimestampMs) return false;
      if (ItemBeenSeen != other.ItemBeenSeen) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (TimestampMs != 0L) hash ^= TimestampMs.GetHashCode();
      if (ItemBeenSeen != 0) hash ^= ItemBeenSeen.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampMs != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TimestampMs);
      }
      if (ItemBeenSeen != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemBeenSeen);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimestampMs);
      }
      if (ItemBeenSeen != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemBeenSeen);
      }
      return size;
    }

    public void MergeFrom(GetInventoryMessage other) {
      if (other == null) {
        return;
      }
      if (other.TimestampMs != 0L) {
        TimestampMs = other.TimestampMs;
      }
      if (other.ItemBeenSeen != 0) {
        ItemBeenSeen = other.ItemBeenSeen;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TimestampMs = input.ReadInt64();
            break;
          }
          case 16: {
            ItemBeenSeen = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
